version: '2'
services:
  backend:
    user: 1000:1000
    container_name: quotesRestAPI
    image: quote_api
    mem_limit: 350m
    mem_reservation: 250M
    restart: unless-stopped
    build: .
    ports:
      - "9093:9093"
    volumes:
      - /home/media/quotes:/var/quotes/
    environment:
      - JAVA_OPTS=-Xmx180m
      - SECURITY_USER=${SECURITY_USER}
      - SECURITY_PASSWORD=${SECURITY_PASSWORD}
      - RUNTIME_ENV=prod
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_URL=${QUOTE_DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}